CREATE TABLE `invoices`(
`ID` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
`USER_ID` BIGINT(20)UNSIGNED NOT NULL,
`CUSTOMER_ID` BIGINT(20)UNSIGNED NOT NULL,
`DISCOUNT` VARCHAR(15) NOT NULL,
`VAT` VARCHAR(15) NOT NULL,
`TOTAL` VARCHAR(20) NOT NULL,
`CREATED_AT` TIMESTAMP NOT NULL DEFAULT current_timestamp(),
`UPDATED_AT` TIMESTAMP NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
FOREIGN KEY(`USER_ID`) REFERENCES `user`(`ID`) ON DELETE RESTRICT ON UPDATE CASCADE,
FOREIGN KEY(`CUSTOMER_ID`) REFERENCES `customers`(`ID`) ON DELETE RESTRICT ON UPDATE CASCADE
)