CREATE TABLE `products`(
`ID` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
`USER_ID` BIGINT(20)UNSIGNED NOT NULL,
`CATEGORY_ID` BIGINT(20)UNSIGNED NOT NULL,
`NAME` VARCHAR(20) NOT NULL,
`PRICE` VARCHAR(15) NOT NULL,
`UNIT` VARCHAR(15) NOT NULL,
`IMG_URL` VARCHAR(255) NOT NULL,
`CREATED_AT` TIMESTAMP NOT NULL DEFAULT current_timestamp(),
`UPDATED_AT` TIMESTAMP NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
FOREIGN KEY(`USER_ID`) REFERENCES `user`(`ID`) ON DELETE RESTRICT ON UPDATE CASCADE,
FOREIGN KEY(`CATEGORY_ID`) REFERENCES `categories`(`ID`) ON DELETE RESTRICT ON UPDATE CASCADE
)