CREATE TABLE `product_invoice`(
`ID` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
`USER_ID` BIGINT(20)UNSIGNED NOT NULL,
`INVOICE_ID` BIGINT(20)UNSIGNED NOT NULL,
`PRODUCT_ID` BIGINT(20)UNSIGNED NOT NULL,
`QTY` VARCHAR(15) NOT NULL,
`SALE_PRICE` VARCHAR(15) NOT NULL,
`TOTAL` VARCHAR(20) NOT NULL,
`CREATED_AT` TIMESTAMP NOT NULL DEFAULT current_timestamp(),
`UPDATED_AT` TIMESTAMP NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
FOREIGN KEY(`USER_ID`) REFERENCES `user`(`ID`) ON DELETE RESTRICT ON UPDATE CASCADE,
FOREIGN KEY(`INVOICE_ID`) REFERENCES `invoices`(`ID`) ON DELETE RESTRICT ON UPDATE CASCADE,
FOREIGN KEY(`PRODUCT_ID`) REFERENCES `products`(`ID`) ON DELETE RESTRICT ON UPDATE CASCADE
)